# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a501dae8bedca0ecfaf8812b5460cd68"
name = "agent-helper"
application_url = "https://example.com"
embedded = false

[webhooks]
api_version = "2024-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_orders,read_orders,write_customers,read_customers,write_inventory,read_inventory"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
